language: go
sudo: required
dist: trusty

go:
  - 1.7.x
  - 1.8.x
  - tip


before_install:
  - go get -u github.com/alecthomas/gometalinter


install:
  - gometalinter --install


script:
  - hack/repo-infra/verify/verify-go-src.sh -r $(pwd) -v
  - hack/repo-infra/verify/verify-boilerplate.sh 

