language: go
sudo: required
dist: xenial

go:
  - 1.12.x

os:
  - linux
  - linux-ppc64le
  - windows

go_import_path: github.com/kubernetes-sigs/cri-tools

services:
  - docker

before_install:
  - |
    (
      set -Eeuo pipefail
      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        choco install -y make mingw
        export PATH="/c/tools/mingw64/bin:/c/ProgramData/chocolatey/bin;$PATH"
      fi
    )

install:
  - make install.tools

jobs:
  include:
    - stage: Static check
      os: linux
      script:
        - make lint
        - hack/verify-go-modules.sh
    - stage: Static check
      os: linux-ppc64le
      script:
        - make lint
        - hack/verify-go-modules.sh
    - stage: Build
      os: linux
      script:
        -  make release
    - stage: Build
      os: linux-ppc64le
      script:
        -  make release
    - stage: Test
      os: linux
      script:
        - make
        - travis_wait hack/install-docker.sh
        - travis_wait hack/install-kubelet.sh
        - cp build/bin/ginkgo $GOPATH/bin
        - sudo env PATH=$PATH GOPATH=$GOPATH hack/run-critest.sh
    - stage: Test
      os: linux-ppc64le
      script:
        - make
        - travis_wait hack/install-docker.sh
        - travis_wait hack/install-kubelet.sh
        - cp build/bin/ginkgo $GOPATH/bin
        - sudo env PATH=$PATH GOPATH=$GOPATH hack/run-critest.sh
    - stage: Test
      os: windows
      script:
        - make windows
        - powershell -c "Set-ExecutionPolicy Bypass -Scope CURRENTUSER -Force"
        - travis_wait powershell hack/install-kubelet.ps1
        # Skip hack/run-critest.sh temporarily.

stages:
  - Static check
  - Build
  - Test
