language: go
sudo: required
dist: trusty

go:
  - "1.10.2"

go_import_path: github.com/kubernetes-sigs/cri-tools

services:
  - docker

before_install:
  - hack/install-docker.sh
  - hack/install-kubelet.sh

install:
  - make install.tools

jobs:
  include:
    - stage: Static check
      script:
        - make lint
        - make gofmt
    - stage: Build
      script:
        - make release
    - stage: Test
      script:
        - make
        - sudo env PATH=$PATH GOPATH=$GOPATH hack/run-critest.sh
